version: '3.8'

services:
  api:
    container_name: ${PROJECT}_api
    tty: true
    build: .
    ports:
      - ${HOST_PORT}:3000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - common_network

  mysql:
    container_name: ${PROJECT}_mysql
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Kolkata
    networks:
      - common_network

  phpmyadmin:
    container_name: ${PROJECT}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=3000000000
      - TZ=Asia/Kolkata
    networks:
      - common_network

networks:
  common_network:
    name: common_network
